### PR TITLE
Implement MakeCall and RecieveCall

### PR DESCRIPTION
**Pull request by Satnet**
I have tried many different complex libraries whitout any luck. They dont work seemlessly. Your library works very good and is simple! Please implement RecieveCall and MakeCall. In my case answering is not needed. I simply need the code to recieve a call and display the phone number.
For making call it should call untill the reciever answers or hungs up. I think many people would appreciate this. Thanks!

### CODE REVIEW

**Comment by meirm** [comment]
I will add that functionality during the week, thanks for the note.

**Comment by Satnet** [comment]
Hello.

Thank you very much. Much appreciated!

Cheers

lördag 20 februari 2016 skrev Meir Michanie notifications@github.com:

> I will add that functionality during the week, thanks for the note.
> 
> On Fri, 19 Feb 2016 at 22:24 Satnet <notifications@github.com

**Comment by TR4811** [comment]
Who are you and why are you sending me this info?

Tom Roper
Chief General Counsel
Millennium Risk Managers LLC

**Comment by TR4811** [comment]
Who are you and why are you sending me this email?

Tom Roper
Chief General Counsel
Millennium Risk Managers LLC

**Comment by meirm** [comment]
Make and Receive phone call done.

**Comment by Satnet** [comment]
This is Amazing! I will try this out. Thanks allot for doing this so fast mate!

**Pull request closed without merging**
